version: '3'

services:

  #React Nextjs Node Service

  node:

    image: webskittersdocker/node20:latest

    container_name: emory-ui-NextJS

    restart: unless-stopped

    working_dir: /home/wtsadmin/myapp

    environment:

      - NODE_ENV=production

    
    volumes:

      - ./:/home/wtsadmin/myapp

    ports:

      - "14128:14128"
    command: >
      sh -c "npm i --force &&
             npm run build &&
             npm start"


#Docker Networks

networks:
  default:
    external:
      name: webskitters
